### ISSUE TITLE
Embedded metrics in ECS task configured with awslogs Log Driver

### ISSUE THREAD

**Issue by jhecking** [awslabs/aws-embedded-metrics-python#13]
Is it possible to use this client to generate embedded metrics in an ECS task that's configured with the awslogs Log Driver? Like in a Lambda environment, the task just logs to stdout and the logs are automatically collected and send to CloudWatch. So the LambdaSink should work just as well for the ECS environment as well. The problem, I guess, is in the environment detection. Unlike the Lambda environment, I don't think it's possible to automatically detect the ECS task environment as there are no special env vars set (AFAIK). And even if that's possible, then the next challenge would be to detect whether the awslogs Log Driver is being used. So probably the configuration of the client would have to be done manually for the ECS task environment.

Would a PR for this feature likely be accepted?

**Comment by jaredcnance** [comment]
Great question @jhecking. That's mostly correct. In order to support the awslogs driver, we would need to modify the driver to include the `x-amzn-logs-format` header described [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html). Right now we have no plans to modify the driver since ECS is recommending moving to [FireLens](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-launches-firelens-log-router-for-amazon-ecs-and-aws-fargate/) (which uses FluentBit), instead of the awslogs driver. We do plan to support EMF in the [amazon-cloudwatch-logs-for-fluent-bit](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/issues/27) project soon. 

From the perspective of this library, we probably just need to provide a simple setup for this scenario that allows you to explicitly configure which sink the logs are sent to without going through the environment detection step. 

We won't begin work on this for another 1-2 weeks, but PRs in the meantime are certainly welcome 😃.

**Comment by jhecking** [comment]
Great. Thanks for the quick response and for the pointer to the fluent bit ticket. I'll be monitoring that. For now, we have decided to just use the CloudWatch PutMetricData API directly.

**Comment by jaredcnance** [comment]
Closing this issue. We're tracking the FireLens integration here: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/pull/42. Additionally, you can configure the CWAgent to run on ECS/EKS as described [here](https://github.com/aws-samples/amazon-cloudwatch-container-insights/tree/master/ecs-task-definition-templates/deployment-mode) and configure it to send embedded metrics as decribed [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_CloudWatch_Agent.html#CloudWatch_Embedded_Metric_Format_Generation_Install_Agent).

**Comment by gordonpn** [comment]
@jhecking 

Any EMF logs that can reach CloudWatch Logs will now be parsed and metrics can be generated from them. You don't need the EMF header anymore.

If you face any issues, you can get in touch with me!

**Comment by anayak-cmt** [comment]
@gordonpn Does it mean we can use awslogs driver to emit EMF logs (no need to use awsfirelens log driver)

**Comment by gordonpn** [comment]
> @gordonpn Does it mean we can use awslogs driver to emit EMF logs (no need to use awsfirelens log driver as was suggested in one of the earlier comments)

@anayak-cmt, yes that is what that means.

You need to write your EMF logs to stdout and get them to CloudWatch Logs. One of the many ways to do that is with the awslogs driver. When your EMF logs reach CWL, they will be processed and metrics will be published.

**Comment by skidson** [comment]
> @jhecking
> 
> Any EMF logs that can reach CloudWatch Logs will now be parsed and metrics can be generated from them. You don't need the EMF header anymore.

This _needs_ to be made clear in AWS' documentation on EMF. This solved a big headache for me trying to get EMF working for my AWS Batch application which makes sidecar containers difficult/impossible but logging to CW trivial. Sadly I spent at least a day fiddling around with CW Agent before finding this.
